### ISSUE TITLE
Amount editable

### ISSUE THREAD

**Issue by rvdsteege** [wp-pay-extensions/contact-form-7#12]
From customer:

> I see that it is possible to adjust the amount (pronamic_pay_amount) via DevTools. This amount is then visible at Mollie's checkout. Wouldn't it be better to get the value for `pronamic_pay_amount` from the raw `post_content` of CF7? That way you can get the amount from the original field shortcode and pass that amount on to Mollie.

@LeoOosterloo asks in https://github.com/pronamic/pronamic-pay-with-mollie-for-contact-form-7/issues/14 if we can do something about this.

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/2325939497/26014/_

**Comment by remcotolsma** [comment]
Decided for now that this is Contact Form 7 territory and not for us to resolve. Our customer received the following update:

> Bedankt voor je bericht. Dit lijkt een beperking te zijn in de Contact Form 7 validatie van [checkboxes, radio buttons en select menu's](https://contactform7.com/checkboxes-radio-buttons-and-menus/). Met alleen Contact Form 7 hebben bezoekers van een formulier de mogelijkheid om stiekem de waarden aan te passen via bijvoorbeeld developer tools. We hadden verwacht dat Contact Form 7 gebruikers hier misschien wel eerder eens melding van hebben gemaakt richting de ontwikkelaar. We konden echter op https://wordpress.org/support/plugin/contact-form-7/ en https://github.com/rocklobster-in/contact-form-7/issues niet direct gerelateerde issues/topics vinden. Mocht je dit echt dwars zitten dan kun je altijd overwegen om daar zelf een issue/topic te openen. We hebben wel overwogen om bijvoorbeeld zelf de validatie van o.a. het bedragveld aan te scherpen, maar dat lost het probleem niet altijd helemaal op. Als je bijvoorbeeld ook een veld hebt voor het aantal producten, tickets, personen, etc. kunnen bezoekers alsnog de boel manipuleren. Als website beheerder / verkoper zal dit ongetwijfeld opvallen, dus waarschijnlijk zal het niet snel tot serieuze problemen leiden. Daarom hebben we voor nu besloten om geen complexiteit toe te voegen aan onze integratie die dit 'gebrek' half zou afvangen. Eventueel kun je ook een programmeur inschakelen om via WordPress/PHP filters de validatie aan te scherpen: https://contactform7.com/2015/03/28/custom-validation/. Hopelijk is het zo duidelijk, mocht je toch nog vragen/opmerkingen/ideeën hebben dan horen we dat natuurlijk graag. Ook als je dit probleem gaat aankaarten bij de Contact Form 7 ontwikkelaar blijven we daar graag van op de hoogte. Alvast bedankt en veel succes met je Contact Form 7 betalingsformulieren.
