### ISSUE TITLE
Use `$submission->get_posted_data()` to retrieve data?

### ISSUE THREAD

**Issue by remcotolsma** [wp-pay-extensions/contact-form-7#14]
> Apart from this, I do think that we can improve the retrieval of the submitted data by using `$submission->get_posted_data()` for example:
> 
> https://github.com/pronamic/wp-pronamic-pay-contact-form-7/blob/6a5af57b34bbbe8637b10c363d6b3e6f231bfdbf/src/Pronamic.php#L170-L187
> 
> This might save some code in handling the tags and pipes?
> 
> https://github.com/rocklobster-in/contact-form-7/blob/2cfaa472fa485c6d3366fcdd80701fdaf7f9e425/includes/submission.php#L370-L463

_Originally posted by @remcotolsma in https://github.com/pronamic/wp-pronamic-pay-contact-form-7/issues/13#issuecomment-1689886315_

**Comment by rvdsteege** [comment]
In https://wordpress.org/support/topic/cf7-form-not-going-to-payment-screen/, the following piped select value doesn't seem to be working (anymore?):

```
[select* prijsveld pronamic_pay_amount use_label_element free_text "Maak een keuze" "Yogaweekend Charneux (€395,-)|395"]
```

This could possibly also be resolved by using the submission posted data methods.
