### ISSUE TITLE
Add support for currencies

### ISSUE THREAD

**Issue by rvdsteege** [wp-pay-extensions/contact-form-7#20]
From customer, who wants to use the currency `CHF` to accept payments through Twint:

> How can I define the currency?

Currently, only payments in `EUR` are supported — the default currency of the https://github.com/pronamic/wp-money library.

https://github.com/pronamic/wp-pronamic-pay-contact-form-7/blob/3dffa328a4dfe660125cdc7571c1b361f710f3d8/src/Pronamic.php#L61-L97

There are multiple ways to achieve multi-currency:
- add a filter like `pronamic_pay_contact_form_7_currency`
- add `pronamic_pay_currency` field option
- add a general default currency plugin setting
- ...

@remcotolsma, thoughts?

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/2708876062/27722_

**Comment by remcotolsma** [comment]
I searched for "contact form 7 currency setting" and came across https://contactform7.com/2015/02/27/using-values-from-a-form-tag/ . In that regard you would think a `pronamic_pay_currency` field option would be a good choice. Admins could possibly let visitors choose their own currency or define a different currency in a hidden field?
