### ISSUE TITLE
Flamingo not storing submission with Pronamic Pay

### ISSUE THREAD

**Issue by EmkeDevani** [wp-pay-extensions/contact-form-7#22]
When i add Pronamic Pay to my Contact Form 7, the submission isn't stored to Flamingo. Without Pronamic Pay or amount=0, it will store the submission. Within the payment overview not all the fields are visible. Is this a know bug with the CF7 module?

**Comment by EmkeDevani** [comment]
Adding 'pronamic_pay_redirect' to the flamingo states will fix this and store the submission:

```
add_filter( 'wpcf7_flamingo_submit_if', function( $states ) {
  $states[] = 'pronamic_pay_redirect';
  return $states;
} );
```

**Comment by rvdsteege** [comment]
Happy to see you were able to resolve the issue yourself already, @EmkeDevani!

@remcotolsma what do you think, should we filter `wpcf7_flamingo_submit_if` and add `pronamic_pay_redirect` by default?

**Comment by remcotolsma** [comment]
I am not yet familiar with the `wpcf7_flamingo_submit_if` filter.

https://github.com/rocklobster-in/contact-form-7/blob/39cd37df1c3840c745476346b9f3f6b853850400/modules/flamingo.php#L1-L26

If I understand correctly, we give the Contact Form 7 submission the status `pronamic_pay_redirect` when payment is required?

https://github.com/pronamic/wp-pronamic-pay-contact-form-7/blob/ab3a1d766b0c23eebecbfb883ac392b628197254/src/Extension.php#L156-L176

The Flamingo plugin only saves the submission if the status is `spam`, `mail_sent` or `mail_failed`?

Then it seems to me that it would indeed be a nice improvement to add `pronamic_pay_redirect` to it via the `wpcf7_flamingo_submit_if` filter.
